### PR TITLE
Jw/final tweaks

### PR DESCRIPTION
**Pull request by jonashw**
These are final changes that I promised to do for Dave, as discussed.

### CODE REVIEW

**Comment by jonashw** [comment]
The ci/cd build is failing on the npm install step.  I have not added any packages in these commits AFAIK.

**Comment by jonashw** [comment]
@srkirkland 
The ci/cd build is failing on the npm install step. I have not added any packages in these commits AFAIK.

**Comment by srkirkland** [comment]
@jonashw it seems your PR includes 29,000+ changes to the package-lock.json file that npm install uses, despite no changes to the package.json file.  I'm sure that's the reason for the failure, but i haven't looked into your changes to see why.  Perhaps the best idea would be to revert those package-lock changes unless you have a good reason for wanting to make that many changes.

**Comment by jonashw** [comment]
I don't know why package-lock changed so much but reverting it fixed the issue.  Thanks. 

Merge?

**Comment by jonashw** [comment]
@srkirkland I don't know why package-lock changed so much but reverting it fixed the issue. Thanks.

Merge?

**Comment by srkirkland** [comment]
@jonashw 🚀 merge away

**Pull request merged**
